@extends('layout')
@section('title','Usuarios')
@section('content')
    @if(!empty($users))
        <table>
            <thead>
            <tr>
                <th>Nombre</th>
                <th>E-mail</th>
                <th>DNI</th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->dni}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endif
    @endsection
